site_name: Reimaden Mods Documentation
site_description: Information about Maxmani's mods for Minecraft.
site_url: https://docs.reimaden.net

repo_url: https://github.com/Maxmani/reimaden-mods-documentation

nav:
  - Home: index.md
  - Arcadian Dream:
    - Introduction: arcadian-dream/introduction.md
    - Features:
      - Danmaku: arcadian-dream/features/danmaku.md
      - Mobs: arcadian-dream/features/mobs.md
      - Ritual Crafting: arcadian-dream/features/ritual-crafting.md
    - Miscellaneous:
      - Advancement Triggers:
        - Ritual Crafting: arcadian-dream/misc/advancement-triggers/ritual-crafting.md
        - Danmaku Modified: arcadian-dream/misc/advancement-triggers/danmaku-modified.md
        - Bullets Cancelled: arcadian-dream/misc/advancement-triggers/bullets-cancelled.md
  - Voile:
    - Introduction: voile/introduction.md
    - General Types:
      - Power Types:
        - Convert Entity: voile/types/power-types/convert-entity.md
        - Enchantment Vulnerability: voile/types/power-types/enchantment-vulnerability.md
        - Flip Model: voile/types/power-types/flip-model.md
        - Instant Effect Immunity: voile/types/power-types/instant-effect-immunity.md
        - Modify Behavior: voile/types/power-types/modify-behavior.md
        - Modify Death Sound: voile/types/power-types/modify-death-sound.md
        - Modify Divergence: voile/types/power-types/modify-divergence.md
        - Modify Footstep Sound: voile/types/power-types/modify-footstep-sound.md
        - Modify Hurt Sound: voile/types/power-types/modify-hurt-sound.md
        - Modify Scale: voile/types/power-types/modify-scale.md
        - Reverse Instant Effects: voile/types/power-types/reverse-instant-effects.md
        - Zombie Arms: voile/types/power-types/zombie-arms.md
    - Action Types:
      - Entity Action Types:
        - Change Resource With Status Effects: voile/types/entity-action-types/change-resource-with-status-effects.md
    - Condition Types:
      - Entity Condition Types:
        - Moon Phase: voile/types/entity-condition-types/moon-phase.md
        - Precise On Block: voile/types/entity-condition-types/precise-on-block.md
      - Item Condition Types:
        - Enchantability: voile/types/item-condition-types/enchantability.md
theme:
  name: material
  favicon: assets/icon.gif
  logo: assets/icon.gif
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.tabs
    - toc.follow
    - navigation.top
markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - abbr
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - toc:
      permalink: "#"
plugins:
  - search:
      lang: en
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
  - git-revision-date-localized:
      type: timeago
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Maxmani
      name: GitHub
  alternate:
    - name: English
    # link: /en/
    # Uncomment once there's some language options
      lang: en